In [1]:
import numpy as np

In [2]:
x1=np.array([[1,2,3],[4,5,6]])
print(x1.shape)

(2, 3)


In [3]:
arr2=np.array([[1,2],[3,4],[5,6]])
print(arr2.shape)

(3, 2)


In [5]:
arr2=np.array([[1,2,3,4],[3,4,2,4],[4,5,6,7]])
print(arr2.shape)

(3, 4)


In [8]:
arr2.shape=(4,3)
arr2

array([[1, 2, 3],
       [4, 3, 4],
       [2, 4, 4],
       [5, 6, 7]])

In [10]:
arr2.size

12

In [11]:
arr4=np.zeros((3,2))
arr4

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [12]:
arr5=np.zeros((3,2),dtype=int)
arr5

array([[0, 0],
       [0, 0],
       [0, 0]])

In [14]:
arr6=np.ones((3,2))
arr6

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [15]:
arr6=np.ones((3,2),dtype=int)
arr6

array([[1, 1],
       [1, 1],
       [1, 1]])

In [16]:
arr7=np.array([[[1,2,3,4],[3,4,2,4],[4,5,6,7]],[[2,3,2,4],[4,3,5,2],[3,4,2,4]]])
print(arr7.shape)

(2, 3, 4)


In [17]:
arr7


array([[[1, 2, 3, 4],
        [3, 4, 2, 4],
        [4, 5, 6, 7]],

       [[2, 3, 2, 4],
        [4, 3, 5, 2],
        [3, 4, 2, 4]]])

In [18]:
arr8=np.arange(2,10,2)
arr8

array([2, 4, 6, 8])

In [19]:
arr8=np.arange(2,11,2)
arr8

array([ 2,  4,  6,  8, 10])

In [20]:
arr9=np.arange(1,10,2)
arr9

array([1, 3, 5, 7, 9])

In [21]:
arr8=np.arange(1,10,0.5)
arr8

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [24]:
arr10=np.array([[1,21,3],[43,5,6],[76,8,95]])
arr10

array([[ 1, 21,  3],
       [43,  5,  6],
       [76,  8, 95]])

In [25]:
np.amin(arr10,1)

array([1, 5, 8])

In [26]:
np.amin(arr10,0)

array([1, 5, 3])

In [27]:
arr10=np.array([[1,21,3],[43,5,6],[76,8,95]])
arr10

array([[ 1, 21,  3],
       [43,  5,  6],
       [76,  8, 95]])

In [28]:
np.amax(arr10,0)

array([76, 21, 95])

In [31]:
arr12=np.array([[2,3,4],[2,3,4]])
np.mean(arr12)

3.0

In [33]:
np.median(arr12)

3.0

In [34]:
np.average(arr12)

3.0

In [35]:
np.var(arr12)

0.6666666666666666

In [36]:
np.std(arr12)

0.816496580927726

In [51]:
arr14=np.array([[1,2,3],[3,4,5],[6,7,8],[2,3,4]])
print(arr14.shape)
print(np.average(arr14))
print(np.mean(arr14))
print(np.median(arr14))
print(np.std(arr14))
print(np.var(arr14))
print(np.min(arr14,0))
print(np.min(arr14,1))
print(np.max(arr14,0))
print(np.max(arr14,1))
print(np.min(arr14))
print(np.max(arr14))

(4, 3)
4.0
4.0
3.5
2.041241452319315
4.166666666666667
[1 2 3]
[1 3 6 2]
[6 7 8]
[3 5 8 4]
1
8


In [58]:
a1=np.array([[1,1],[2,2]])
a2=np.array([[3,3],[4,4]])
print("a1:",a1)
print("a2:",a2)
print("addition of 2 arrays is:\n",a1+a2)
print("subtraction of 2 arrays is:\n",a1-a2)
print("division of 2 arrays is:\n",a1/a2)
print("multiplication of 2 arrays is:\n",a1*a2)
print(" matrix multiplication of 2 arrays is:\n",a1@a2)
print(" matrix multiplication of 2 arrays is:\n",a1.dot(a2))
print("transpose of 2 arrays is:\n",a1.transpose())

a1: [[1 1]
 [2 2]]
a2: [[3 3]
 [4 4]]
addition of 2 arrays is:
 [[4 4]
 [6 6]]
subtraction of 2 arrays is:
 [[-2 -2]
 [-2 -2]]
division of 2 arrays is:
 [[0.33333333 0.33333333]
 [0.5        0.5       ]]
multiplication of 2 arrays is:
 [[3 3]
 [8 8]]
 matrix multiplication of 2 arrays is:
 [[ 7  7]
 [14 14]]
 matrix multiplication of 2 arrays is:
 [[ 7  7]
 [14 14]]
transpose of 2 arrays is:
 [[1 2]
 [1 2]]


In [1]:
import pandas as pd

In [4]:
data=[13,25,33,42,55.3]
s=pd.Series(data)
print(s)

0    13.0
1    25.0
2    33.0
3    42.0
4    55.3
dtype: float64


In [13]:
#DataFrame
dict={'Name':['rama','ravi','raju','latha','varsha','harsha','siri','priya'],'Roll no':[10,20,35,34,53,23,22,18],'Age':[13,19,25,27,27,18,32,25],'Dpt':['It','cse','ai','aiml','ds','ece','iot','mca']}
print(dict)

{'Name': ['rama', 'ravi', 'raju', 'latha', 'varsha', 'harsha', 'siri', 'priya'], 'Roll no': [10, 20, 35, 34, 53, 23, 22, 18], 'Age': [13, 19, 25, 27, 27, 18, 32, 25], 'Dpt': ['It', 'cse', 'ai', 'aiml', 'ds', 'ece', 'iot', 'mca']}


In [14]:
df=pd.DataFrame(dict)
df

Name  Roll no  Age   Dpt
0    rama       10   13    It
1    ravi       20   19   cse
2    raju       35   25    ai
3   latha       34   27  aiml
4  varsha       53   27    ds
5  harsha       23   18   ece
6    siri       22   32   iot
7   priya       18   25   mca

In [15]:
df.head()

Name  Roll no  Age   Dpt
0    rama       10   13    It
1    ravi       20   19   cse
2    raju       35   25    ai
3   latha       34   27  aiml
4  varsha       53   27    ds

In [17]:
df.tail()

Name  Roll no  Age   Dpt
3   latha       34   27  aiml
4  varsha       53   27    ds
5  harsha       23   18   ece
6    siri       22   32   iot
7   priya       18   25   mca

In [18]:
df.head(3)

Name  Roll no  Age  Dpt
0  rama       10   13   It
1  ravi       20   19  cse
2  raju       35   25   ai

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   Name     8 non-null      object
 1   Roll no  8 non-null      int64 
 2   Age      8 non-null      int64 
 3   Dpt      8 non-null      object
dtypes: int64(2), object(2)
memory usage: 388.0+ bytes


In [20]:
df.describe()

Roll no        Age
count   8.000000   8.000000
mean   26.875000  23.250000
std    13.357047   6.112049
min    10.000000  13.000000
25%    19.500000  18.750000
50%    22.500000  25.000000
75%    34.250000  27.000000
max    53.000000  32.000000

In [22]:
df['Name']

0      rama
1      ravi
2      raju
3     latha
4    varsha
5    harsha
6      siri
7     priya
Name: Name, dtype: object

In [24]:
df['Age']

0    13
1    19
2    25
3    27
4    27
5    18
6    32
7    25
Name: Age, dtype: int64

In [25]:
df[['Name','Age']]

Name  Age
0    rama   13
1    ravi   19
2    raju   25
3   latha   27
4  varsha   27
5  harsha   18
6    siri   32
7   priya   25

In [26]:
df.loc[0]

Name       rama
Roll no      10
Age          13
Dpt          It
Name: 0, dtype: object

In [27]:
df.iloc[0]

Name       rama
Roll no      10
Age          13
Dpt          It
Name: 0, dtype: object

In [30]:
df[df['Age']>20]

Name  Roll no  Age   Dpt
2    raju       35   25    ai
3   latha       34   27  aiml
4  varsha       53   27    ds
6    siri       22   32   iot
7   priya       18   25   mca

In [35]:
df['Age']=df['Age']+2
df

Name  Roll no  Age   Dpt
0    rama       10   15    It
1    ravi       20   21   cse
2    raju       35   27    ai
3   latha       34   29  aiml
4  varsha       53   29    ds
5  harsha       23   20   ece
6    siri       22   34   iot
7   priya       18   27   mca

In [40]:
dict={'Name':['rama','ravi','raju','latha','varsha','harsha','siri','priya'],'Roll no':[10,20,35,None,53,23,22,18],'Age':[13,19,None,27,27,18,32,25],'Dpt':['It','cse','ai','aiml','ds','ece','iot','mca']}
df=pd.DataFrame(dict)
df

Name  Roll no   Age   Dpt
0    rama     10.0  13.0    It
1    ravi     20.0  19.0   cse
2    raju     35.0   NaN    ai
3   latha      NaN  27.0  aiml
4  varsha     53.0  27.0    ds
5  harsha     23.0  18.0   ece
6    siri     22.0  32.0   iot
7   priya     18.0  25.0   mca

In [41]:
df.dropna()

Name  Roll no   Age  Dpt
0    rama     10.0  13.0   It
1    ravi     20.0  19.0  cse
4  varsha     53.0  27.0   ds
5  harsha     23.0  18.0  ece
6    siri     22.0  32.0  iot
7   priya     18.0  25.0  mca

In [42]:
df.fillna(1)

Name  Roll no   Age   Dpt
0    rama     10.0  13.0    It
1    ravi     20.0  19.0   cse
2    raju     35.0   1.0    ai
3   latha      1.0  27.0  aiml
4  varsha     53.0  27.0    ds
5  harsha     23.0  18.0   ece
6    siri     22.0  32.0   iot
7   priya     18.0  25.0   mca

In [44]:
df.sort_values(by='Roll no')#sorting rollno

Name  Roll no   Age   Dpt
0    rama     10.0  13.0    It
7   priya     18.0  25.0   mca
1    ravi     20.0  19.0   cse
6    siri     22.0  32.0   iot
5  harsha     23.0  18.0   ece
2    raju     35.0   NaN    ai
4  varsha     53.0  27.0    ds
3   latha      NaN  27.0  aiml

In [46]:
df.sort_values(by='Name')#sorting names

Name  Roll no   Age   Dpt
5  harsha     23.0  18.0   ece
3   latha      NaN  27.0  aiml
7   priya     18.0  25.0   mca
2    raju     35.0   NaN    ai
0    rama     10.0  13.0    It
1    ravi     20.0  19.0   cse
6    siri     22.0  32.0   iot
4  varsha     53.0  27.0    ds

In [48]:
#add an other column
df['Marks']=[50,23,56,67,54,67,44,34]
df

Name  Roll no   Age   Dpt  Marks
0    rama     10.0  13.0    It     50
1    ravi     20.0  19.0   cse     23
2    raju     35.0   NaN    ai     56
3   latha      NaN  27.0  aiml     67
4  varsha     53.0  27.0    ds     54
5  harsha     23.0  18.0   ece     67
6    siri     22.0  32.0   iot     44
7   priya     18.0  25.0   mca     34